### ISSUE TITLE
Enhancement: Remove the 'What is the name of the GitHub repo where this will be published? (my-electrode-component)'

### ISSUE THREAD

**Issue by jspears** [electrode-io/generator-electrode-component#10]
Is nearly a duplicate  of this question. These should be the same 99% of the time.  So why ask the question. Save questions for bigger code splits.

What is your Package/GitHub project name? (e.g., 'wysiwyg-component') my-electrode-component

**Comment by ananavati** [comment]
enhanced in https://github.com/electrode-io/generator-electrode-component/pull/15
