### ISSUE TITLE
Enhancement: Port configuration

### ISSUE THREAD

**Issue by jspears** [electrode-io/generator-electrode-component#13]
I would assume there would be many component dev environments running at any given time.  So it would be great if the http listen port was configurable via environment and/or config section in the package.json.

``` sh
$ HTTP_PORT=4001 gulp dev
$ HTTP_PORT=4002 npm start
```

//package.json

``` json
"config": {
   "electrode":{
     "port":4002
   }
}
```

**Comment by ananavati** [comment]
@jspears 

fixed in https://github.com/electrode-io/electrode-archetype-react-component/pull/19

`WEBPACK_DEVSERVER_PORT` will be the env variable used to provide custom port.

example: ***`$ WEBPACK_DEVSERVER_PORT=4002 gulp dev`***

**Comment by ananavati** [comment]
add the feature in https://github.com/electrode-io/electrode-archetype-react-component/pull/19
