### ISSUE TITLE
Gulp Check error

### ISSUE THREAD

**Issue by nakie** [electrode-io/generator-electrode-component#14]
Ran into an issue working through an example in the docs ( http://www.electrode.io/docs/create_reusable_component.html ) and got the following error on `gulp check` 

> -d was unexpected at this time.

I was able to duplicate this by running the following

    yo electrode-component

    gulp check

resulting in a string of errors referencing the message above 

Here is the full output of gulp check 

> gulp check
> [14:57:01] Using gulpfile ~\Documents\Dev\my-electrode-component\gulpfile.js
> [14:57:01] Starting 'check'...
> [14:57:01] Starting 'check-dep'...
> Check dependencies passed
> [14:57:01] Finished 'check-dep' after 167 ms
> [14:57:01] Starting 'lint'...
> [14:57:01] Starting 'lint-stylus'...
> -d was unexpected at this time.
> [14:57:01] 'lint-stylus' errored after 7.12 ms
> [14:57:01] Error: command exit code 1
>     at error (C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\shelljs\src\exec.js:180:7
>     at ChildProcess.exithandler (child_process.js:220:5)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> [14:57:01] 'check' errored after 181 ms
> [14:57:01] Error in plugin 'run-sequence(lint-stylus)'
> Message:
>     command exit code 1
> Details:
>     stdout:
>     stderr: -d was unexpected at this time.
> 
> Stack:
> Error: command exit code 1
>     at error (C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\shelljs\src\exec.js:180:7
>     at ChildProcess.exithandler (child_process.js:220:5)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> [14:57:01] 'lint' errored after 16 ms
> [14:57:01] Error in plugin 'run-sequence(check)'
> Message:
>     command exit code 1
> Details:
>     stdout:
>     stderr: -d was unexpected at this time.
> 
> Stack:
> Error: command exit code 1
>     at error (C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\shelljs\src\exec.js:180:7
>     at ChildProcess.exithandler (child_process.js:220:5)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> [14:57:01] 'lint' errored after 20 ms
> [14:57:01] Error in plugin 'run-sequence(lint-stylus)'
> Message:
>     command exit code 1
> Details:
>     stdout:
>     stderr: -d was unexpected at this time.
> 
> Stack:
> Error: command exit code 1
>     at error (C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29
>     at C:\Users\Nathan\Documents\Dev\my-electrode-component\node_modules\shelljs\src\exec.js:180:7
>     at ChildProcess.exithandler (child_process.js:220:5)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
>

**Comment by ananavati** [comment]
closing this bug and merging into https://github.com/electrode-io/electrode-archetype-react-component/issues/15
