### ISSUE TITLE
Update documentation to include information about internationalization

### ISSUE THREAD

**Issue by ghost** [electrode-io/generator-electrode-component#18]
It appears that the internationalization provided by the generator is not included in any documentation (if it is, please point me in the right direction). It would be helpful to have this included in the documentation as well as instructions for removing it or adding to it. 

The concept of multi-tenancy is also not discussed in the documentation, but shows up under src\lang\tenants (as well as other places).

**Comment by ananavati** [comment]
@whoisjonniegalt 

thanks for checking out electrode and yep internationalization & multi-tenancy even though exist in electrode, the docs for L10N & multi-tenancy could use some attention along with providing some usage examples.

opened up a github issue and added it to our list of things-to-do https://github.com/electrode-io/electrode-io.github.io/issues/358
