### ISSUE TITLE
Enhancment: Use the directory name as the repo name default

### ISSUE THREAD

**Issue by jspears** [electrode-io/generator-electrode-component#9]
``` sh
$ What is your Package/GitHub project name? (e.g., 'wysiwyg-component') (wysiwyg-component)
```

should be 

``` sh
$ What is your Package/GitHub project name? (e.g.,'my-electrode-component') (my-electrode-component)
```

where my-electrode-component is the name of your component.

**Comment by donsalari** [comment]
@jspears :  
Should the generator always pick up the current folder name as a default for the component name?  
In that case, if the dev is the parent folder of components, the generator will always select the parent name.
